### ISSUE TITLE
CSS parsing of valid CSS files fails

### ISSUE THREAD

**Issue by mscofield0** [paginagmbh/EPUB-Checker#76]
I use TailwindCSS with my epub project to style the book. However, stuff that are usually legal that Tailwind produces, don't pass the epub checker's validator. I assume that the parser doesn't fully conform to the CSS standard, or there are some limitations in the EPUB standard that I'm missing.

**Comment by tofi86** [comment]
This seems to be an issue with the underlaying `epubcheck` EPUB validator. Please open an issue with them in their repo: https://github.com/w3c/epubcheck
