### ISSUE TITLE
Epub checker 5.0.1

### ISSUE THREAD

**Issue by GuruSeenu** [paginagmbh/EPUB-Checker#88]
Hi I came across that one of the warning that is not flaged in the new checker version but in the older checker version it shows. I have received the feedback from the client. could you please check and confirm?
![2 0 6_validation](https://github.com/paginagmbh/EPUB-Checker/assets/137040885/bb0cb5a4-5448-402c-b70a-d20de63575fe)
![2 0 9_validation](https://github.com/paginagmbh/EPUB-Checker/assets/137040885/525bf849-d580-404b-9bdc-c78c880bde50)

**Comment by br-pagina** [comment]
We do not have control over the messages output by the underlying EPUBCheck. This must have been caused by a change in EPUBCheck between version 4.2.6 and 5.0.1. Please check the release notes of the EPUBCheck project (https://github.com/w3c/epubcheck).
